#!/usr/bin/env bash
set -euo pipefail

: "${PR_DOCS_DIR:?PR_DOCS_DIR is required}"

CONTEXT_JSON="$PR_DOCS_DIR/context.json"
if [[ ! -f "$CONTEXT_JSON" ]]; then
  echo "::error::Missing context file: $CONTEXT_JSON"
  exit 1
fi

ACTION="$(jq -r '.action' "$CONTEXT_JSON")"
PR_NUMBER="$(jq -r '.pr_number' "$CONTEXT_JSON")"
TITLE="$(jq -r '.title' "$CONTEXT_JSON")"
MERGED="$(jq -r '.merged' "$CONTEXT_JSON")"
PUSH_CONTEXT_AVAILABLE="$(jq -r '.push_context_available' "$CONTEXT_JSON")"

FULL_SHORTSTAT="$(cat "$PR_DOCS_DIR/full_shortstat.txt")"
PUSH_SHORTSTAT="$(cat "$PR_DOCS_DIR/push_shortstat.txt")"

if [[ -z "${FULL_SHORTSTAT//[[:space:]]/}" ]]; then
  FULL_SHORTSTAT="No full diff shortstat available."
fi
if [[ -z "${PUSH_SHORTSTAT//[[:space:]]/}" ]]; then
  PUSH_SHORTSTAT="N/A"
fi

if [[ "$ACTION" == "closed" ]]; then
  if [[ "$MERGED" == "true" ]]; then
    STATE_LINE="PR closed as merged."
  else
    STATE_LINE="PR closed without merge."
  fi
else
  STATE_LINE="PR action: $ACTION."
fi

if [[ "$ACTION" == "synchronize" && "$PUSH_CONTEXT_AVAILABLE" == "true" ]]; then
  THIS_PUSH_LINE="$PUSH_SHORTSTAT"
  COMMIT_SOURCE_FILE="$PR_DOCS_DIR/push_commits.txt"
else
  THIS_PUSH_LINE="No incremental push delta for this event."
  COMMIT_SOURCE_FILE="$PR_DOCS_DIR/full_commits.txt"
fi

# Keep commit list concise and predictable.
COMMITS="$(sed -n '1,10p' "$COMMIT_SOURCE_FILE")"
if [[ -z "${COMMITS//[[:space:]]/}" || "$COMMITS" == "N/A" ]]; then
  COMMITS="- No commit list available."
fi

cat > "$PR_DOCS_DIR/generated_block.md" <<EOF_BLOCK
## At a Glance
- #${PR_NUMBER}: ${TITLE}
- ${STATE_LINE}
- Full PR diff: ${FULL_SHORTSTAT}

## This Push
- ${THIS_PUSH_LINE}

## Review Focus
- Validate behavior against changed areas listed below.
- Confirm edge cases and regressions in touched components.
- Verification status is not shown in this fallback summary.

## Details
$(sed -n '1,12p' "$PR_DOCS_DIR/full_diff_stat.txt" | sed 's/^/- /')

## Commits
${COMMITS}

---
_Autogenerated fallback (Gemini usage limit reached)._ 
EOF_BLOCK

echo "Fallback PR docs generated."
