#!/usr/bin/env bash
set -euo pipefail

: "${PR_DOCS_DIR:?PR_DOCS_DIR is required}"
: "${DOCS_MODE:?DOCS_MODE is required}"

CONTEXT_JSON="$PR_DOCS_DIR/context.json"
if [[ ! -f "$CONTEXT_JSON" ]]; then
  echo "::error::Missing context file: $CONTEXT_JSON"
  exit 1
fi

ACTION="$(jq -r '.action' "$CONTEXT_JSON")"
PR_NUMBER="$(jq -r '.pr_number' "$CONTEXT_JSON")"
TITLE="$(jq -r '.title' "$CONTEXT_JSON")"
MERGED="$(jq -r '.merged' "$CONTEXT_JSON")"
HEAD_SHORT="$(jq -r '.head_short // "unknown"' "$CONTEXT_JSON")"
PUSH_CONTEXT_AVAILABLE="$(jq -r '.push_context_available' "$CONTEXT_JSON")"

FULL_SHORTSTAT="$(cat "$PR_DOCS_DIR/full_shortstat.txt")"
PUSH_SHORTSTAT="$(cat "$PR_DOCS_DIR/push_shortstat.txt")"
PUSH_COMMITS="$(sed -n '1,8p' "$PR_DOCS_DIR/push_commits.txt")"
PUSH_FILES="$(sed -n '1,12p' "$PR_DOCS_DIR/push_name_status.txt")"
FULL_COMMITS="$(sed -n '1,12p' "$PR_DOCS_DIR/full_commits.txt")"
FULL_FILES="$(sed -n '1,14p' "$PR_DOCS_DIR/full_name_status.txt")"

if [[ -z "${FULL_SHORTSTAT//[[:space:]]/}" || "$FULL_SHORTSTAT" == "N/A" ]]; then
  FULL_SHORTSTAT="No full diff shortstat available."
fi

if [[ -z "${PUSH_SHORTSTAT//[[:space:]]/}" || "$PUSH_SHORTSTAT" == "N/A" ]]; then
  PUSH_SHORTSTAT="Push delta unavailable for this event."
fi

if [[ -z "${PUSH_COMMITS//[[:space:]]/}" || "$PUSH_COMMITS" == "N/A" ]]; then
  PUSH_COMMITS="- No push commit list available."
fi
if [[ -z "${PUSH_FILES//[[:space:]]/}" || "$PUSH_FILES" == "N/A" ]]; then
  PUSH_FILES="- No push file list available."
fi
if [[ -z "${FULL_COMMITS//[[:space:]]/}" || "$FULL_COMMITS" == "N/A" ]]; then
  FULL_COMMITS="- No commit list available."
fi
if [[ -z "${FULL_FILES//[[:space:]]/}" || "$FULL_FILES" == "N/A" ]]; then
  FULL_FILES="- No file list available."
fi

if [[ "$ACTION" == "closed" ]]; then
  if [[ "$MERGED" == "true" ]]; then
    STATE_LINE="closed and merged"
  else
    STATE_LINE="closed without merge"
  fi
else
  STATE_LINE="$ACTION"
fi

if [[ "$DOCS_MODE" == "push_comment" ]]; then
  if [[ "$PUSH_CONTEXT_AVAILABLE" != "true" ]]; then
    cat > "$PR_DOCS_DIR/generated_block.md" <<EOF_COMMENT
- Push delta unavailable for this event.

---
_Autogenerated fallback (Groq unavailable)._
EOF_COMMENT
  else
    cat > "$PR_DOCS_DIR/generated_block.md" <<EOF_COMMENT
- Push $HEAD_SHORT
- Delta: $PUSH_SHORTSTAT
- Commits in this push:
$PUSH_COMMITS
- Files touched in this push:
$(printf '%s\n' "$PUSH_FILES" | sed 's/^/- /')

---
_Autogenerated fallback (Groq unavailable)._
EOF_COMMENT
  fi
elif [[ "$DOCS_MODE" == "body" ]]; then
  cat > "$PR_DOCS_DIR/generated_block.md" <<EOF_BODY
- PR #$PR_NUMBER: $TITLE
- Event: $STATE_LINE
- Net diff: $FULL_SHORTSTAT
- Key commits:
$FULL_COMMITS
- Main touched files:
$(printf '%s\n' "$FULL_FILES" | sed 's/^/- /')

---
_Autogenerated fallback (Groq unavailable)._
EOF_BODY
else
  echo "::error::Unsupported DOCS_MODE: $DOCS_MODE"
  exit 1
fi

echo "Fallback docs generated."
